= Resource Group Controller
:github: https://github.com/ten1010-io/resource-group-controller

== Abstract


Resource Group Controller is Kubernetes controller which has below responsibilities.

* Automates task for allocating specific node based on namespace.
* Automates creation and allocation of Role and ClusterRole for namespace administrator’s general authorities.

== Installation


* prerequisites
** availability on kubectl command
** cluster admin authority for ClusterRole

** Check out release tag to use pre-build image on DockerHub without building the sources directly.

*** e.g. git checkout tags/v1.0.0

//-

. Project clone
+
----
git clone https://github.com/ten1010-io/resource-group-controller
cd resource-group-controller
# checkout branch or tag you want to use
# e.g. git checkout tags/v1.0.0
----

. Build source
+
----
./build-images.sh
# must distribute image to all nodes on cluster
----


. Setup up certificates and deploy on kubernetes cluster
+
----
cd kuberntes/controller/cert
./configure.sh
cd ..
kubectl apply -k .
----



== Usage


All cases describe with ResourceGroup custom resource.

* case 1 : restricts specific nodes to only be used in given namespaces
+
The following example is for limit node1 only for namespace ns1.
----
apiVersion: resource-group.ten1010.io/v1beta1
kind: ResourceGroup
metadata:
  name: group1
spec:
  nodes: ["node1"]
  namespaces: ["ns1"]
  daemonSet:
    daemonSets: []
  subjects: []
----

* case 2 : register DaemonSet
+
The following example is for letting specific Pod of DaemonSet schedules on Resource Group’s Node.
+
Unlike namespaces, permissions for daemon sets defined in daemonSet field are not assigned to the subject of the Resource Group.
+
----
apiVersion: resource-group.ten1010.io/v1beta1
kind: ResourceGroup
metadata:
  name: group1
spec:
  nodes: ["node1"]
  namespaces: ["ns1"]
  daemonSet:
    daemonSets:
      - namespace: ds1
        name: ds1
  subjects: []
----

* case 3 : create and assign Role and RoleBinding of namespace administrator
+
The following example is for granting over namespace ns1 authority to User user1.
+
----
apiVersion: resource-group.ten1010.io/v1beta1
kind: ResourceGroup
metadata:
  name: group1
spec:
  nodes: ["node1"]
  namespaces: ["ns1"]
  daemonSet:
    daemonSets: []
  subjects:
    - apiGroup: "rbac.authorization.k8s.io"
      kind: "User"
      name: "user1"
----



== Automatically creating Role

Namespace administrator’s Role is automatically created for given Resource Group, when Resource Group is created, all existing subjects from subject field are assigned as well.

The automatically created Role includes CRUD authorities against all below resources existing on namespaces managed by Resource Group.

----
1. core api
    1. Pod
    2. Service
    3. ConfigMap
    4. Secret
    5. PersistentVolumeClaim
    6. ServiceAccount
    7. LimitRange
    8. Event
    9. ReplicationController
2. events.k8s.io api
    1. Event
3. batch api
    1. Job
    2. CronJob
4. apps api
    1. Deployment
    2. StatefulSet
    3. Daemonset
    4. ReplicaSet
5. autoscaling api
    1. HorizontalPodAutoscaler
6. policy api
    1. PodDisruptionBudget
----

== Supporting workload controller

----
1. batch/CronJob
2. apps/Daemonset
3. apps/Deployment
4. batch/Job
5. apps/ReplicaSet
6. core/ReplicationController
7. apps/StatefulSet
----

== Reporting security vulnerability

DO NOT REPORT ON ISSUES.

Find any vulnerabilities related with security, please report on hyeongdeok.yoon@ten1010.io.

== Reporting Bug, suggesting improvement, or any questions

Find any bugs, any suggestions or questions, please open Github Issues.

== License

Apache License, Version 2.0