spring:
  application:
    name: project-controller
  profiles:
    active: "production"
  web:
    resources:
      add-mappings: false

server:
  forward-headers-strategy: framework

app:
  k8s:
    verify-ssl: true
    kube-config:
      mode: FILE
      kube-config-path: "/Users/joon/.kube/config"
  aipub:
    enabled: true
    server-url: "https://k10s.cluster9.idc1.ten1010.io"
    verifying-ssl: false
    username: "testuser"
    password: "asdasdasd"

logging.level.io.ten1010.aipub: DEBUG