apiVersion: apps/v1
kind: Deployment
metadata:
  name: resource-group-controller
spec:
  template:
    spec:
      containers:
        - name: resource-group-controller
          resources:
            requests: {}
            limits: {}
---
apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: resource-group-controller.resource-group.ten1010.io
webhooks:
  - name: resource-group-controller.resource-group.ten1010.io
    clientConfig:
      caBundle: ### To be patched ###
---
