apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: project-controller.project.aipub.ten1010.io
rules:
  - apiGroups: [ "*" ]
    resources: [ "*" ]
    verbs: [ "*" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: project-controller.project.aipub.ten1010.io
subjects:
  - kind: ServiceAccount
    namespace: project-controller
    name: project-controller
roleRef:
  kind: ClusterRole
  name: project-controller.project.aipub.ten1010.io
  apiGroup: rbac.authorization.k8s.io
---
