apiVersion: v1
kind: Service
metadata:
  name: resource-group-controller
spec:
  type: ClusterIP
  selector:
    app: resource-group-controller
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
