apiVersion: v1
kind: Service
metadata:
  name: project-controller
spec:
  type: ClusterIP
  selector:
    app: project-controller
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
---
