apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: resource-group-controller.resource-group.ten1010.io
webhooks:
  - name: resource-group-controller.resource-group.ten1010.io
    admissionReviewVersions: ["v1"]
    clientConfig:
      caBundle: <CA_BUNDLE>
      service:
        namespace: resource-group-controller
        name: resource-group-controller
        path: /validate
        port: 8080
    failurePolicy: Ignore
    matchPolicy: Equivalent
    namespaceSelector: {}
    objectSelector: {}
    rules:
      - apiGroups:   ["resource-group.ten1010.io"]
        apiVersions: ["v1beta1"]
        operations:  ["CREATE", "UPDATE"]
        resources:   ["resourcegroups", "ResourceGroup"]
        scope: "*"
    sideEffects: None
    timeoutSeconds: 10
---
