apiVersion: project.aipub.ten1010.io/v1alpha1
kind: Project
metadata:
  name: proj1
spec:
  members:
    - aipubUser: au1
      role: project-manager
      id: "9"
    - aipubUser: au1
      role: project-manager
      id: "8"
    - aipubUser: au1
      role: project-manager
    - aipubUser: au2
      role: project-developer
  quota:
    pvcStorage:
  binding:
    nodes:
      - minikube
    nodeGroups:
      # - ng1
    imageHubs:
      - img-hub1
---
